---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
        run: docker-compose up -d && docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        env:
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
        run: docker-compose run --rm app sh -c "flake8"

